services:
  streamlit-app:
    build:
      context: ./app_front
      dockerfile: Dockerfile
    ports:
      - "${STREAMLIT_PORT:-8501}:8501"
    env_file:
      - .env
    networks:
          - app_network
  api-app:
    build: ./app_api
    container_name: mon_api
    ports:
      - "${FASTAPI_PORT}:${FASTAPI_PORT}"
    environment:
      - FASTAPI_PORT=${FASTAPI_PORT}
    env_file:
      - .env
    restart: always
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port $$FASTAPI_PORT"
    networks:
      - app_network

  database:
    image: postgres:15-alpine
    container_name: postgres_container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT : ${POSTGRES_PORT}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      # Persistance des données (le volume survit à l'arrêt du conteneur)
      - db_data:/var/lib/postgresql/data

    networks:
      - app_network

volumes:
  db_data: # Déclaration du volume nommé

networks:
  app_network:
    driver: bridge