services:
  streamlit-app:
    build:
      context: ./app_front
      dockerfile: Dockerfile
    ports:
      - "${STREAMLIT_PORT}:8501"
    env_file:
      - .env
    networks:
          - app_network
  api-app:
    build: ./app_api
    container_name: mon_api
    ports:
      - "${FASTAPI_PORT}:8000" 
    networks:
      - app_network
    command: uvicorn child_api:app --host 0.0.0.0 --port 8000

networks:
  app_network:
    driver: bridge