services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${FASTAPI_PORT:-8000}:${FASTAPI_PORT:-8000}"
    # volumes:
    #   - ./app_api:/app
    environment:
      - FASTAPI_PORT=${FASTAPI_PORT:-8000}
    restart: always