name: Deploiement Docker

# Déclenche le script à chaque "git push" sur la branche main
on:
  push:
    branches: [ "main" ]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: app_front

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install uv app_front
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          cache-dependency-glob: "app_front/uv.lock"

      # 3. Lance les tests (Pytest)
      # Si cette étape échoue, le déploiement s'arrête immédiatement
      - name: Run Tests
        run: |
          uv sync --frozen --all-extras
          uv run pytest

      # 4. Connexion au Docker Hub (utilise tes Secrets GitHub)
      - name: Login to Docker Hub
        if: success()
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 5. Build l'image Docker et l'envoie sur le Hub
      - name: Build and Push
        if: success()
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # Remplace par ton pseudo Docker Hub et ton nom d'image
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mon-app-python:latest