name: Deploy Documentation


on:
  push:
    branches: [main]


permissions:
  contents: write
  pages: write
  id-token: write


jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"

      - name: Install Dependencies
        run: |
          # 1. On installe les dépendances de la doc (Sphinx, Furo, Myst, etc.)
          uv sync --project docs

          # 1. On cherche tous les pyproject.toml dans les sous-dossiers
          # 2. On extrait les dépendances de chaque fichier
          # 3. On installe tout via pip
          find . -name "pyproject.toml" -exec sed -n '/dependencies = \[/,/\]/p' {} + \
            | grep -E '"[^"]+"' | sed 's/[",]//g' | xargs -r pip install

      - name: Generate API skeleton
        run: |
          mkdir -p docs/source
          # On boucle sur tous les dossiers commençant par app_
          for dir in app_*; do
            if [ -d "$dir" ]; then
              echo "Génération de la doc pour : $dir"
              # Création d'un sous-dossier dans docs/source pour éviter les collisions
              mkdir -p docs/source/$dir
              sphinx-apidoc -f -o docs/source/$dir ./$dir
            fi
          done

      # 2. GÉNÉRER LE HTML
      - name: Build Sphinx Documentation
        env:
          # On définit la racine comme chemin de recherche Python
          PYTHONPATH: ${{ github.workspace }}
        run: |
          mkdir -p public
          # Génération du HTML
          # -n : mode strict pour voir les erreurs de liens
          sphinx-build -n -b html docs/source public

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'public'

  deploy-docs:
    needs: build-docs
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4