name: Extraction d'informations
on:
  push:
    branches: [ main, dev , 'feat/**']  # Branch to survey

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        matrix:
            python-version: ["3.11"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install uv app_front
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          cache-dependency-glob: "app_front/uv.lock"

      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync --frozen --all-extras

      # --- EXTRACTION DE LA VERSION ---
      - name: Extract Project Version
        id: get_version
        run: |
          VERSION=$(grep -m 1 '^version = ' pyproject.toml | cut -d '"' -f 2)
          echo "PROJECT_VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "### 🚀 Version du projet : v$VERSION" >> $GITHUB_STEP_SUMMARY

      # --- MISE À JOUR DU README (C'est ici qu'on utilise la variable) ---
      - name: Inject Variables into README
        run: |
          # On récupère les valeurs pour les utiliser dans sed
          # On utilise l'ID 'get_version' défini juste au-dessus
          VERSION="${{ steps.get_version.outputs.PROJECT_VERSION }}"
          USER="${{ github.repository_owner }}"
          REPO="${{ github.event.repository.name }}"
          EMAIL="lio.jourdhier@gmail.com"
          
          # On copie le template vers le vrai README avant de remplacer
          cp README.template.md README.md
          cp .github/CODE_OF_CONDUCT.template.md .github/CODE_OF_CONDUCT.md
          cp .github/CONTRIBUTING.template.md .github/CONTRIBUTING.md
          
          # On remplace les marqueurs dans le fichier README.md
          sed -i "s/%VERSION%/$VERSION/g" README.md
          sed -i "s/%USER%/$USER/g" README.md
          sed -i "s/%REPO%/$REPO/g" README.md

          # Mise à jour du Code de Conduite 
          sed -i "s/%EMAIL%/$EMAIL/g" .github/CODE_OF_CONDUCT.md
          sed -i "s/%REPO%/$REPO/g" .github/CODE_OF_CONDUCT.md

          # Mise à jour de CONTRIBUTING.md
          sed -i "s/%VERSION%/$VERSION/g" .github/CONTRIBUTING.md
          sed -i "s/%USER%/$USER/g" .github/CONTRIBUTING.md
          sed -i "s/%REPO%/$REPO/g" .github/CONTRIBUTING.md

      - name: Commit and Push README
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add README.md
          git add .github/CODE_OF_CONDUCT.md
          git add .github/CONTRIBUTING.md

          git commit -m "docs: auto-update variables to v${{ steps.get_version.outputs.PROJECT_VERSION }} [skip ci]" || echo "No changes"
          git push