name: Python Tests
on:
  push:
    branches: [ main, dev , 'feat/**']  # Branch to survey

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build_app:
    runs-on: ubuntu-latest
    strategy:
        matrix:
            python-version: ["3.11"]
    defaults:
      run:
        working-directory: app_front

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install uv app_front
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          cache-dependency-glob: "app_front/uv.lock"

      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync --frozen --all-extras

      - name: Run all tests
        run: |
          # Exécution et capture
          uv run pytest --cov=app --cov-report=term-missing --cov-report=json:coverage.json | tee pytest_report.txt
          
          # Extraction du % pour le step summary
          COV_PERCENT=$(grep 'TOTAL' pytest_report.txt | awk '{print $NF}')
          echo "## 📈 Résumé de Couverture : $COV_PERCENT" >> $GITHUB_STEP_SUMMARY
          grep -A 10 "Name" pytest_report.txt >> $GITHUB_STEP_SUMMARY

      - name: Archive Code Coverage Results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: |
            pytest_report.txt
            htmlcov/